# Generated by Django 2.2.6 on 2019-11-05 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSpec',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('app_token', models.TextField()),
            ],
        ),
    ]
