# Generated by Django 2.2.6 on 2019-11-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appspec',
            name='public_key',
        ),
    ]
