# Generated by Django 2.2.6 on 2019-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppManagement', '0002_remove_appspec_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200)),
                ('app_token', models.CharField(max_length=200)),
                ('redirect_url', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=100)),
            ],
        ),
    ]
