# Generated by Django 2.2.6 on 2019-11-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppManagement', '0003_loginrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
