# Generated by Django 2.2.6 on 2019-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('name', models.TextField()),
            ],
        ),
    ]
