# Generated by Django 2.2.6 on 2019-12-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
