# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevAuthNotificationSE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevAuthNotificationSE
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'reactnativeapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactnativeapp
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

  target 'reactnativeappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativeapp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactnativeapp-tvOS

  target 'reactnativeapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end